#!/usr/bin/env node
/**
 * Updates Elasticsearch index with pre-computed similar artworks
 * 
 * This script:
 * 1. Reads similar_artworks.jsonl generated by script 7
 * 2. Updates each artwork document with its similar_artworks field
 * 3. Uses bulk update API for efficiency
 */

import { loadEnvConfig } from '@next/env';
import * as fs from 'fs/promises';
import * as path from 'path';
import { createReadStream } from 'fs';
import { createInterface } from 'readline';
import { parseArgs } from 'util';
import { getElasticsearchClient, INDEX_NAME } from '../../lib/elasticsearch/client';

// Load environment variables
const projectDir = path.join(__dirname, '../..');
loadEnvConfig(projectDir);

interface SimilarArtwork {
  id: string;
  similarity_type: string;
  confidence: number;
  explanation: string;
  source: string;
}

interface ProcessedRecord {
  id: string;
  similar_artworks: SimilarArtwork[];
  generated_at: string;
}

class SimilarityUpdater {
  private similarArtworksPath: string;
  private processedCount = 0;
  private errorCount = 0;
  
  constructor(similarArtworksPath: string) {
    this.similarArtworksPath = similarArtworksPath;
  }
  
  async loadSimilarArtworks(): Promise<Map<string, SimilarArtwork[]>> {
    const similarityMap = new Map<string, SimilarArtwork[]>();
    
    try {
      await fs.access(this.similarArtworksPath);
      const fileStream = createReadStream(this.similarArtworksPath);
      const rl = createInterface({
        input: fileStream,
        crlfDelay: Infinity
      });

      for await (const line of rl) {
        if (line.trim()) {
          try {
            const record = JSON.parse(line) as ProcessedRecord;
            similarityMap.set(record.id, record.similar_artworks);
          } catch (e) {
            console.error('Error parsing line:', e);
          }
        }
      }
      
      console.log(`Loaded similar artworks for ${similarityMap.size} artworks`);
    } catch (error) {
      console.error('Error loading similar artworks file:', error);
      throw error;
    }
    
    return similarityMap;
  }
  
  async updateIndex(batchSize: number = 100): Promise<void> {
    const client = getElasticsearchClient();
    const similarityMap = await this.loadSimilarArtworks();
    
    if (similarityMap.size === 0) {
      console.log('No similar artworks to update');
      return;
    }
    
    console.log(`\nUpdating ${similarityMap.size} artworks in Elasticsearch...`);
    
    // Convert to array for batching
    const entries = Array.from(similarityMap.entries());
    
    for (let i = 0; i < entries.length; i += batchSize) {
      const batch = entries.slice(i, i + batchSize);
      const operations = [];
      
      // Build bulk update operations
      for (const [artworkId, similarArtworks] of batch) {
        operations.push(
          { update: { _index: INDEX_NAME, _id: artworkId } },
          { doc: { similar_artworks: similarArtworks } }
        );
      }
      
      try {
        const bulkResponse = await client.bulk({
          operations,
          refresh: false // Don't force refresh for better performance
        });
        
        // Check for errors
        if (bulkResponse.errors) {
          const errorItems = bulkResponse.items.filter(item => 
            item.update?.error
          );
          console.error(`Batch ${Math.floor(i / batchSize) + 1} had ${errorItems.length} errors`);
          this.errorCount += errorItems.length;
        }
        
        this.processedCount += batch.length;
        
        if ((i + batchSize) % 1000 === 0 || i + batchSize >= entries.length) {
          console.log(`Progress: ${this.processedCount}/${entries.length} updated`);
        }
      } catch (error) {
        console.error(`Error updating batch starting at ${i}:`, error);
        this.errorCount += batch.length;
      }
    }
    
    // Force a refresh at the end to make changes searchable
    console.log('\nRefreshing index...');
    await client.indices.refresh({ index: INDEX_NAME });
    
    console.log('\nUpdate complete!');
    console.log(`Successfully updated: ${this.processedCount - this.errorCount}`);
    console.log(`Errors: ${this.errorCount}`);
  }
  
  async verifyUpdate(sampleSize: number = 5): Promise<void> {
    const client = getElasticsearchClient();
    const similarityMap = await this.loadSimilarArtworks();
    
    console.log(`\nVerifying update with ${sampleSize} samples...`);
    
    // Get random sample of artwork IDs
    const artworkIds = Array.from(similarityMap.keys());
    const sampleIds = artworkIds
      .sort(() => Math.random() - 0.5)
      .slice(0, sampleSize);
    
    for (const artworkId of sampleIds) {
      try {
        const response = await client.get({
          index: INDEX_NAME,
          id: artworkId,
          _source: ['id', 'title', 'artist', 'similar_artworks']
        });
        
        const artwork = response._source as any;
        const expectedSimilar = similarityMap.get(artworkId)?.length || 0;
        const actualSimilar = artwork.similar_artworks?.length || 0;
        
        console.log(`\n${artwork.title} by ${artwork.artist}:`);
        console.log(`  Expected ${expectedSimilar} similar artworks`);
        console.log(`  Found ${actualSimilar} similar artworks`);
        
        if (actualSimilar > 0 && artwork.similar_artworks[0]) {
          console.log(`  Top match: ${artwork.similar_artworks[0].explanation}`);
        }
      } catch (error) {
        console.error(`Error verifying ${artworkId}:`, error);
      }
    }
  }
}

async function main() {
  const { values } = parseArgs({
    options: {
      'batch-size': { type: 'string', short: 'b' },
      verify: { type: 'boolean', short: 'v' },
      'verify-count': { type: 'string' },
      help: { type: 'boolean', short: 'h' }
    }
  });
  
  if (values.help) {
    console.log(`
Update Elasticsearch Index with Similar Artworks

This script reads the similar_artworks.jsonl file and updates each
artwork document in Elasticsearch with its pre-computed similar artworks.

Usage: npm run 8-update-similarities-met -- [options]

Options:
  -b, --batch-size <n>    Bulk update batch size (default: 100)
  -v, --verify            Verify update with sample documents
  --verify-count <n>      Number of samples to verify (default: 5)
  -h, --help             Show this help

Examples:
  # Update all artworks
  npm run 8-update-similarities-met
  
  # Update with larger batches for speed
  npm run 8-update-similarities-met -- --batch-size 500
  
  # Update and verify with 10 samples
  npm run 8-update-similarities-met -- --verify --verify-count 10

Note: This script requires that similar_artworks.jsonl has been
generated by running script 7 first.
`);
    process.exit(0);
  }
  
  const similarArtworksPath = path.join(__dirname, '../../data/met/similar_artworks.jsonl');
  
  // Check if input file exists
  try {
    await fs.access(similarArtworksPath);
  } catch {
    console.error('Error: similar_artworks.jsonl not found');
    console.error('Please run script 7 first: npm run 7-generate-similar-artworks-met');
    process.exit(1);
  }
  
  const updater = new SimilarityUpdater(similarArtworksPath);
  const batchSize = values['batch-size'] ? parseInt(values['batch-size']) : 100;
  
  console.log('Elasticsearch Similarity Updater');
  console.log('================================');
  console.log(`Index: ${INDEX_NAME}`);
  console.log(`Batch size: ${batchSize}`);
  console.log();
  
  // Update the index
  await updater.updateIndex(batchSize);
  
  // Optionally verify
  if (values.verify) {
    const verifyCount = values['verify-count'] ? parseInt(values['verify-count']) : 5;
    await updater.verifyUpdate(verifyCount);
  }
}

if (require.main === module) {
  main().catch(error => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
}