# Elasticsearch configuration for development
network.host: 0.0.0.0
# Enable CORS for browser access
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "Content-Type,Content-Length,Authorization"
http.cors.allow-methods: "GET,POST,PUT,DELETE,OPTIONS,HEAD"